controllers:
    resource: ../src/Controller/
    type: attribute
client :
    path : /client/prenom/{prenom}
    controller : App\Controller\ClientController::info
image_data:
    path: /img/data/{imageName}
    controller: App\Controller\ImageController::affiche
clientAccess:
    path: /client
    controller: App\Controller\ClientController::home
    options:
        ouverture: '9-17'
registration:
    path: /register
    controller: App\Controller\EnregisterController::register
    methods: ['GET', 'POST']

user_profile:
    path: /profile/{login}
    controller: App\Controller\EnregisterController::userProfile
    methods: ['GET']